//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AHDB.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class AHDBContext : DbContext
    {
        public AHDBContext()
            : base("name=AHDBContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Contact> Contacts { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<Note> Notes { get; set; }
        public virtual DbSet<Repair> Repairs { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Vendor> Vendors { get; set; }
        public virtual DbSet<VendorRepair> VendorRepairs { get; set; }
    
        public virtual int spDeleteContact(Nullable<int> contactId)
        {
            var contactIdParameter = contactId.HasValue ?
                new ObjectParameter("ContactId", contactId) :
                new ObjectParameter("ContactId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spDeleteContact", contactIdParameter);
        }
    
        public virtual int spDeleteCustomer(Nullable<int> customerId)
        {
            var customerIdParameter = customerId.HasValue ?
                new ObjectParameter("CustomerId", customerId) :
                new ObjectParameter("CustomerId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spDeleteCustomer", customerIdParameter);
        }
    
        public virtual int spDeleteNote(Nullable<int> noteId)
        {
            var noteIdParameter = noteId.HasValue ?
                new ObjectParameter("NoteId", noteId) :
                new ObjectParameter("NoteId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spDeleteNote", noteIdParameter);
        }
    
        public virtual int spDeleteRepair(Nullable<int> repairId)
        {
            var repairIdParameter = repairId.HasValue ?
                new ObjectParameter("RepairId", repairId) :
                new ObjectParameter("RepairId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spDeleteRepair", repairIdParameter);
        }
    
        public virtual int spDeleteVendor(Nullable<int> vendorId)
        {
            var vendorIdParameter = vendorId.HasValue ?
                new ObjectParameter("VendorId", vendorId) :
                new ObjectParameter("VendorId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spDeleteVendor", vendorIdParameter);
        }
    
        public virtual int spDeleteVendorRepair(Nullable<int> repairId)
        {
            var repairIdParameter = repairId.HasValue ?
                new ObjectParameter("RepairId", repairId) :
                new ObjectParameter("RepairId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spDeleteVendorRepair", repairIdParameter);
        }
    
        public virtual ObjectResult<spGetCustomers_Result> spGetCustomers(Nullable<int> pageNumber, Nullable<int> rowsPerPage)
        {
            var pageNumberParameter = pageNumber.HasValue ?
                new ObjectParameter("PageNumber", pageNumber) :
                new ObjectParameter("PageNumber", typeof(int));
    
            var rowsPerPageParameter = rowsPerPage.HasValue ?
                new ObjectParameter("RowsPerPage", rowsPerPage) :
                new ObjectParameter("RowsPerPage", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spGetCustomers_Result>("spGetCustomers", pageNumberParameter, rowsPerPageParameter);
        }
    
        public virtual int spInsertContact(string description, string firstName, string lastName, string phoneNumber, string cellPhoneNumber, string email, Nullable<int> customerID, Nullable<int> vendorID)
        {
            var descriptionParameter = description != null ?
                new ObjectParameter("Description", description) :
                new ObjectParameter("Description", typeof(string));
    
            var firstNameParameter = firstName != null ?
                new ObjectParameter("FirstName", firstName) :
                new ObjectParameter("FirstName", typeof(string));
    
            var lastNameParameter = lastName != null ?
                new ObjectParameter("LastName", lastName) :
                new ObjectParameter("LastName", typeof(string));
    
            var phoneNumberParameter = phoneNumber != null ?
                new ObjectParameter("PhoneNumber", phoneNumber) :
                new ObjectParameter("PhoneNumber", typeof(string));
    
            var cellPhoneNumberParameter = cellPhoneNumber != null ?
                new ObjectParameter("CellPhoneNumber", cellPhoneNumber) :
                new ObjectParameter("CellPhoneNumber", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            var customerIDParameter = customerID.HasValue ?
                new ObjectParameter("CustomerID", customerID) :
                new ObjectParameter("CustomerID", typeof(int));
    
            var vendorIDParameter = vendorID.HasValue ?
                new ObjectParameter("VendorID", vendorID) :
                new ObjectParameter("VendorID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spInsertContact", descriptionParameter, firstNameParameter, lastNameParameter, phoneNumberParameter, cellPhoneNumberParameter, emailParameter, customerIDParameter, vendorIDParameter);
        }
    
        public virtual int spInsertCustomer(string description, string companyName)
        {
            var descriptionParameter = description != null ?
                new ObjectParameter("Description", description) :
                new ObjectParameter("Description", typeof(string));
    
            var companyNameParameter = companyName != null ?
                new ObjectParameter("CompanyName", companyName) :
                new ObjectParameter("CompanyName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spInsertCustomer", descriptionParameter, companyNameParameter);
        }
    
        public virtual int spInsertNote(string noteText, Nullable<int> repairID)
        {
            var noteTextParameter = noteText != null ?
                new ObjectParameter("NoteText", noteText) :
                new ObjectParameter("NoteText", typeof(string));
    
            var repairIDParameter = repairID.HasValue ?
                new ObjectParameter("RepairID", repairID) :
                new ObjectParameter("RepairID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spInsertNote", noteTextParameter, repairIDParameter);
        }
    
        public virtual int spInsertRepair(string description, string purchaseOrder, string quoteNumber, Nullable<System.DateTime> dueDate, Nullable<int> customerID)
        {
            var descriptionParameter = description != null ?
                new ObjectParameter("Description", description) :
                new ObjectParameter("Description", typeof(string));
    
            var purchaseOrderParameter = purchaseOrder != null ?
                new ObjectParameter("PurchaseOrder", purchaseOrder) :
                new ObjectParameter("PurchaseOrder", typeof(string));
    
            var quoteNumberParameter = quoteNumber != null ?
                new ObjectParameter("QuoteNumber", quoteNumber) :
                new ObjectParameter("QuoteNumber", typeof(string));
    
            var dueDateParameter = dueDate.HasValue ?
                new ObjectParameter("DueDate", dueDate) :
                new ObjectParameter("DueDate", typeof(System.DateTime));
    
            var customerIDParameter = customerID.HasValue ?
                new ObjectParameter("CustomerID", customerID) :
                new ObjectParameter("CustomerID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spInsertRepair", descriptionParameter, purchaseOrderParameter, quoteNumberParameter, dueDateParameter, customerIDParameter);
        }
    
        public virtual int spInsertVendor(string description, string companyName)
        {
            var descriptionParameter = description != null ?
                new ObjectParameter("Description", description) :
                new ObjectParameter("Description", typeof(string));
    
            var companyNameParameter = companyName != null ?
                new ObjectParameter("CompanyName", companyName) :
                new ObjectParameter("CompanyName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spInsertVendor", descriptionParameter, companyNameParameter);
        }
    
        public virtual int spInsertVendorRepair(Nullable<int> repairID, Nullable<int> vendorID)
        {
            var repairIDParameter = repairID.HasValue ?
                new ObjectParameter("RepairID", repairID) :
                new ObjectParameter("RepairID", typeof(int));
    
            var vendorIDParameter = vendorID.HasValue ?
                new ObjectParameter("VendorID", vendorID) :
                new ObjectParameter("VendorID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spInsertVendorRepair", repairIDParameter, vendorIDParameter);
        }
    
        public virtual int spUpdateContact(Nullable<int> contactId, string description, string firstName, string lastName, string phoneNumber, string cellPhoneNumber, string email, Nullable<int> customerID, Nullable<int> vendorID)
        {
            var contactIdParameter = contactId.HasValue ?
                new ObjectParameter("ContactId", contactId) :
                new ObjectParameter("ContactId", typeof(int));
    
            var descriptionParameter = description != null ?
                new ObjectParameter("Description", description) :
                new ObjectParameter("Description", typeof(string));
    
            var firstNameParameter = firstName != null ?
                new ObjectParameter("FirstName", firstName) :
                new ObjectParameter("FirstName", typeof(string));
    
            var lastNameParameter = lastName != null ?
                new ObjectParameter("LastName", lastName) :
                new ObjectParameter("LastName", typeof(string));
    
            var phoneNumberParameter = phoneNumber != null ?
                new ObjectParameter("PhoneNumber", phoneNumber) :
                new ObjectParameter("PhoneNumber", typeof(string));
    
            var cellPhoneNumberParameter = cellPhoneNumber != null ?
                new ObjectParameter("CellPhoneNumber", cellPhoneNumber) :
                new ObjectParameter("CellPhoneNumber", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            var customerIDParameter = customerID.HasValue ?
                new ObjectParameter("CustomerID", customerID) :
                new ObjectParameter("CustomerID", typeof(int));
    
            var vendorIDParameter = vendorID.HasValue ?
                new ObjectParameter("VendorID", vendorID) :
                new ObjectParameter("VendorID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spUpdateContact", contactIdParameter, descriptionParameter, firstNameParameter, lastNameParameter, phoneNumberParameter, cellPhoneNumberParameter, emailParameter, customerIDParameter, vendorIDParameter);
        }
    
        public virtual int spUpdateCustomer(Nullable<int> customerId, string description, string companyName)
        {
            var customerIdParameter = customerId.HasValue ?
                new ObjectParameter("CustomerId", customerId) :
                new ObjectParameter("CustomerId", typeof(int));
    
            var descriptionParameter = description != null ?
                new ObjectParameter("Description", description) :
                new ObjectParameter("Description", typeof(string));
    
            var companyNameParameter = companyName != null ?
                new ObjectParameter("CompanyName", companyName) :
                new ObjectParameter("CompanyName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spUpdateCustomer", customerIdParameter, descriptionParameter, companyNameParameter);
        }
    
        public virtual int spUpdateNote(Nullable<int> noteId, string noteText)
        {
            var noteIdParameter = noteId.HasValue ?
                new ObjectParameter("NoteId", noteId) :
                new ObjectParameter("NoteId", typeof(int));
    
            var noteTextParameter = noteText != null ?
                new ObjectParameter("NoteText", noteText) :
                new ObjectParameter("NoteText", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spUpdateNote", noteIdParameter, noteTextParameter);
        }
    
        public virtual int spUpdateRepair(Nullable<int> repairID, string description, string purchaseOrder, string quoteNumber, Nullable<bool> completed, Nullable<System.DateTime> dateCompleted, Nullable<System.DateTime> dueDate)
        {
            var repairIDParameter = repairID.HasValue ?
                new ObjectParameter("RepairID", repairID) :
                new ObjectParameter("RepairID", typeof(int));
    
            var descriptionParameter = description != null ?
                new ObjectParameter("Description", description) :
                new ObjectParameter("Description", typeof(string));
    
            var purchaseOrderParameter = purchaseOrder != null ?
                new ObjectParameter("PurchaseOrder", purchaseOrder) :
                new ObjectParameter("PurchaseOrder", typeof(string));
    
            var quoteNumberParameter = quoteNumber != null ?
                new ObjectParameter("QuoteNumber", quoteNumber) :
                new ObjectParameter("QuoteNumber", typeof(string));
    
            var completedParameter = completed.HasValue ?
                new ObjectParameter("Completed", completed) :
                new ObjectParameter("Completed", typeof(bool));
    
            var dateCompletedParameter = dateCompleted.HasValue ?
                new ObjectParameter("DateCompleted", dateCompleted) :
                new ObjectParameter("DateCompleted", typeof(System.DateTime));
    
            var dueDateParameter = dueDate.HasValue ?
                new ObjectParameter("DueDate", dueDate) :
                new ObjectParameter("DueDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spUpdateRepair", repairIDParameter, descriptionParameter, purchaseOrderParameter, quoteNumberParameter, completedParameter, dateCompletedParameter, dueDateParameter);
        }
    
        public virtual int spUpdateVendor(Nullable<int> vendorId, string description, string companyName)
        {
            var vendorIdParameter = vendorId.HasValue ?
                new ObjectParameter("VendorId", vendorId) :
                new ObjectParameter("VendorId", typeof(int));
    
            var descriptionParameter = description != null ?
                new ObjectParameter("Description", description) :
                new ObjectParameter("Description", typeof(string));
    
            var companyNameParameter = companyName != null ?
                new ObjectParameter("CompanyName", companyName) :
                new ObjectParameter("CompanyName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spUpdateVendor", vendorIdParameter, descriptionParameter, companyNameParameter);
        }
    
        public virtual int spUpdateVendorRepair(Nullable<int> repairID, Nullable<int> vendorID, Nullable<bool> completed)
        {
            var repairIDParameter = repairID.HasValue ?
                new ObjectParameter("RepairID", repairID) :
                new ObjectParameter("RepairID", typeof(int));
    
            var vendorIDParameter = vendorID.HasValue ?
                new ObjectParameter("VendorID", vendorID) :
                new ObjectParameter("VendorID", typeof(int));
    
            var completedParameter = completed.HasValue ?
                new ObjectParameter("Completed", completed) :
                new ObjectParameter("Completed", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spUpdateVendorRepair", repairIDParameter, vendorIDParameter, completedParameter);
        }
    }
}
