//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AHDB.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Note
    {
        public int ID { get; set; }
        public string NoteText { get; set; }
        public System.DateTime DateCreatedAsUtcTime { get; set; }
        public int RepairID { get; set; }
    
        public virtual Repair Repair { get; set; }
    }
}
