//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AHDB.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceComponent
    {
        public ServiceComponent()
        {
            this.Vendors = new HashSet<Vendor>();
        }
    
        public int Id { get; set; }
        public int ServiceId { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<Vendor> Vendors { get; set; }
        public virtual Service Service { get; set; }
    }
}
