//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AHDB.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vendor
    {
        public Vendor()
        {
            this.Contacts = new HashSet<Contact>();
        }
    
        public int Id { get; set; }
        public string CompanyName { get; set; }
        public Nullable<int> ServiceComponentId { get; set; }
        public Nullable<int> ServiceId { get; set; }
    
        public virtual ICollection<Contact> Contacts { get; set; }
        public virtual ServiceComponent ServiceComponent { get; set; }
        public virtual Service Service { get; set; }
    }
}
